src/accounts/models.py
from datetime import datetime

from flask_security import RoleMixin, UserMixin

from src import bcrypt, db


roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('roles.id'))
        )

class Role(RoleMixin, db.Model):

    __tablename__ = "roles"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return f"<Role {self.name}>"

class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)
    is_confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_at = db.Column(db.DateTime, nullable=True)
    is_active = db.Column(db.Boolean())
    roles = db.relationship('Role',
                            secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic')
                            )
    network_id = db.Column(db.Integer, db.ForeignKey("networks.id"))

    def __init__(self, email, password, network_id, is_admin=False, is_confirmed=False, confirmed_at=None, is_active=True):
        self.email = email
        self.password = bcrypt.generate_password_hash(password).decode('utf-8')
        self.created_at = datetime.now()
        self.is_admin = is_admin
        self.is_confirmed = is_confirmed
        self.confirmed_at = confirmed_at
        self.is_active = is_active
        self.network_id = network_id

    def is_active(self):
        return self.is_active
    
    def has_roles(self, *roles):
        return any(role in self.roles for role in roles)

    def __repr__(self):
        return f"<email {self.email}>"
    
class Network(db.Model):

    __tablename__ = "networks"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    county = db.Column(db.String(80))
    state = db.Column(db.String(80))

    def __init__(self, name, county, state):
        self.name = name
        self.county = county
        self.state = state

    def __repr__(self):
        return f"<Network {self.name}>"

src/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from src.accounts.models import User


class RegisterForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Email(message=None), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", 
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )
    role = SelectField(
        "What is your role?",
        choices=[
            ("investor", "Investor"),
            ("entrepreneur", "Entrepreneur"),
            ("economic_developer", "Economic Development Council"),
            ("economic_developer", "Chamber of Commerce"),
            ("economic_developer", "Nonprofit"),
            ("entrepreneur", "Other"), 
            # Set other to entrepreneur for now because it has least privileges.
            # We can override other to whatever role is most appropriate later
        ],
        validators=[DataRequired()]
    )
    community = SelectField(
        "Which county are you in?",
        choices=[
            ("1", "Clallam County, WA"),
            # ("2", "Jefferson County, WA (LION)"),
        ],
        validators=[DataRequired()]
    )

    def validate(self, extra_validators=None):
        initial_validation = super(RegisterForm, self).validate(extra_validators)
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Passwords must match")
            return False
        return True
    
class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])

src/__init__.py
from decouple import config
from flask import Flask, render_template
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_security import Security, SQLAlchemySessionUserDatastore

app = Flask(__name__, static_url_path='/static', static_folder='static')

app.config.from_object(config("APP_SETTINGS"))

login_manager = LoginManager()
login_manager.init_app(app)

bcrypt = Bcrypt(app)
db = SQLAlchemy(app)
migrate = Migrate(app, db)
mail = Mail(app)

# Registering blueprints
from src.accounts.views import accounts_bp
from src.core.views import core_bp

app.register_blueprint(accounts_bp)
app.register_blueprint(core_bp)

# Importing Models
from src.accounts.models import User, Role

login_manager.login_view = "accounts.login"

user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)
security = Security(app, user_datastore)

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()

@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401

@app.errorhandler(403)
def forbidden(error):
    return render_template("errors/403.html"), 403

@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404

@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

src/accounts/views.py
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user, current_user
from flask_security import SQLAlchemySessionUserDatastore

from src import bcrypt, db
from src.accounts.models import User, Role, Network
from src.accounts.token import confirm_token, generate_token
from src.utils.decorators import logout_required
from src.utils.email import send_email

from .forms import RegisterForm, LoginForm

accounts_bp = Blueprint("accounts", __name__)

user_datastore = SQLAlchemySessionUserDatastore(db.session, User, Role)

@accounts_bp.route("/register", methods=["GET", "POST"])
@logout_required
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        role_name = form.role.data
        network_name = form.community.data

        role = Role.query.filter_by(name=role_name).first()
        network = Network.query.filter_by(name=network_name).first()

        if role:
            user = User(email=form.email.data, password=form.password.data, network_id=network)
            user.roles.append(role)

            db.session.add(user)
            db.session.commit()

        token = generate_token(user.email)
        confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
        html = render_template("accounts/confirm_email.html", confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)
        flash("A confirmation email has been sent via email.", "success")

        if user.has_roles("entrepreneur"):
            return redirect(url_for("core.community"))
        else:
            return redirect(url_for("core.home"))

    return render_template("accounts/register.html", form=form)

@accounts_bp.route("/login", methods=["GET", "POST"])
@logout_required
def login():
    if current_user.is_authenticated:
        flash("You are already logged in.", "info")
        if user.has_roles("entrepreneur"):
            return redirect(url_for("core.community"))
        return redirect(url_for("core.home"))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        # user = User.query.filter_by(email=form.email.data).first()
        user = user_datastore.find_user(email=form.email.data)
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            if user.has_roles("entrepreneur"):
                return redirect(url_for("core.community"))
            return redirect(url_for("core.home"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("accounts/login.html", form=form)
    return render_template("accounts/login.html", form=form)

@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out.", "success")
    return redirect(url_for("accounts.login"))

@accounts_bp.route("/confirm/<token>")
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        flash("Account already confirmed.", "success")
        return redirect(url_for("core.home"))
    email = confirm_token(token)
    user = User.query.filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.confirmed_at = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash("You have confirmed your account. Thanks!", "success")
    else:
        flash("The confirmation link is invalid or has expired.", "danger")
    return redirect(url_for("core.home"))

@accounts_bp.route("/inactive")
@login_required
def inactive():
    if current_user.is_confirmed:
        return redirect(url_for("core.home"))
    return render_template("accounts/inactive.html")

@accounts_bp.route("/resend")
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        flash("Your account has already been confirmed.", "success")
        return redirect(url_for("core.home"))
    token = generate_token(current_user.email)
    confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
    html = render_template("accounts/confirm_email.html", confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash("A new confirmation email has been sent.", "success")
    return redirect(url_for("accounts.inactive"))

src/core/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from src.utils.decorators import check_is_confirmed, roles_required
from src.accounts.models import User

core_bp = Blueprint("core", __name__)

@core_bp.route("/")
@login_required
@check_is_confirmed
@roles_required('admin', 'investor', 'economic_developer')
def home():
    return render_template("core/index.html")

@core_bp.route('/investment')
@login_required
@check_is_confirmed
@roles_required('admin', 'investor', 'economic_developer')
def investment():
    return render_template('core/investment.html')

@core_bp.route('/account')
@login_required
@check_is_confirmed
@roles_required('admin', 'investor', 'entrepreneur', 'economic_developer')
def account():
    user = User.query.get(current_user.id)
    role_name = user.roles[0].name
    return render_template('core/account.html', role_name=role_name)

@core_bp.route('/commerce')
@login_required
@check_is_confirmed
@roles_required('admin', 'economic_developer')
def commerce():
    return render_template('core/commerce.html')

@core_bp.route('/community')
@login_required
@check_is_confirmed
@roles_required('admin', 'investor', 'entrepreneur', 'economic_developer')
def community():
    return render_template('core/community.html')

@core_bp.route('/advisor')
@login_required
@check_is_confirmed
@roles_required('admin', 'investor', 'entrepreneur', 'economic_developer')
def advisor():
    return render_template('core/advisor.html')

@core_bp.route('/events')
@login_required
@check_is_confirmed
@roles_required('admin', 'investor', 'entrepreneur', 'economic_developer')
def events():
    return render_template('core/events.html')

src/templates/accounts/confirm_email.html
<p>
  Welcome! Thanks for signing up. Please follow this link to activate your
  account:
</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br />
<p>Thanks!</p>

src/templates/accounts/inactive.html
{% extends "_base.html" %} {% block content %}

<div class="text-center">
  <h1>Welcome!</h1>
  <br />
  <p>
    You have not confirmed your account. Please check your inbox (and spam
    folder) - you should have received an email with a confirmation link.
  </p>
  <p>
    Didn't get the email?
    <a href="{{ url_for('accounts.resend_confirmation') }}">Resend</a>.
  </p>
</div>

{% endblock %}

src/templates/accounts/login.html
{% extends "_base.html" %}

{% block content %}

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <main class="form-signin w-100 m-auto">
      <form role="form" method="post" action="">
        {{ form.csrf_token }}
        <h1 class="h3 mb-3 fw-normal text-center">👋 Nice to see you</h1>

        <div class="form-floating">
          {{ form.email(placeholder="email", class="form-control mb-2") }}
          {{ form.email.label }}
            {% if form.email.errors %}
              {% for error in form.email.errors %}
              <div class="alert alert-danger" role="alert">
                {{ error }}
              </div>
              {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
          {{ form.password(placeholder="password", class="form-control mb-2") }}
          {{ form.password.label }}
            {% if form.password.errors %}
              {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit" style="background-color: #1bae70">Sign in</button>
        <p class="text-center mt-3">Don't have an account? <a href="{{ url_for('accounts.register') }}" style="color: #1bae70">Register now</a></p>
      </form>
    </main>
  </div>
  <div class="col-md-4"></div>
</div>

{% endblock %}

src/templates/accounts/register.html
{% extends "_base.html" %}

{% block content %}

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <main class="form-signin w-100 m-auto">
      <form role="form" method="post" action="">
        {{ form.csrf_token }}
        <h1 class="h3 mb-3 fw-normal text-center">👋 Hi there</h1>

        <div class="form-floating">
          {{ form.email(placeholder="email", class="form-control mb-2") }}
          {{ form.email.label }}
            {% if form.email.errors %}
              {% for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
          {{ form.password(placeholder="password", class="form-control mb-2") }}
          {{ form.password.label }}
            {% if form.password.errors %}
              {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
          {{ form.confirm(placeholder="Confirm Password", class="form-control mb-2") }}
          {{ form.confirm.label }}
            {% if form.confirm.errors %}
              {% for error in form.confirm.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error }}
                </div>
              {% endfor %}
            {% endif %}
        </div>
        <div class="form-floating">
          {{ form.role(class="form-select mb-2") }}
          {{ form.role.label }}
          {% if form.role.errors %}
            {% for error in form.role.errors %}
              <div class="alert alert-danger" role="alert">
                {{ error }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="form-floating">
          {{ form.community(class="form-select mb-2") }}
          {{ form.community.label }}
          {% if form.community.errors %}
            {% for error in form.community.errors %}
              <div class="alert alert-danger" role="alert">
                {{ error }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <button class="w-100 btn btn-lg btn-primary" style="background-color: #1bae70" type="submit">Sign up</button>
        <p class="text-center mt-3">Already registered? <a href="{{ url_for('accounts.login') }}" style="color: #1bae70">Login now</a></p>
      </form>
    </main>
  </div>
  <div class="col-md-4"></div>
</div>

{% endblock %}

src/templates/accounts/reset_password.html
{% extends "_base.html" %}

{% block content %}
    <h1>Reset Password</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}